# Generated by Django 2.1 on 2018-11-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181103_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='avg_rate',
            field=models.DecimalField(decimal_places=2, default=3.5, max_digits=10),
        ),
    ]
