# Generated by Django 2.1 on 2018-11-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181109_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='s',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_voted',
        ),
        migrations.AddField(
            model_name='server',
            name='contact_id',
            field=models.IntegerField(default=0),
        ),
    ]
