# Generated by Django 2.1 on 2018-11-13 12:19

import birthday.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181110_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date_dayofyear_internal',
            field=models.PositiveSmallIntegerField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=birthday.fields.BirthdayField(),
        ),
    ]
