# Generated by Django 2.1 on 2018-11-13 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181113_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date_dayofyear_internal',
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
