# Generated by Django 2.1 on 2018-11-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181113_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='contact_id',
        ),
        migrations.AddField(
            model_name='server',
            name='clients',
            field=models.ManyToManyField(related_name='clients', to='accounts.Client'),
        ),
    ]
